### ISSUE TITLE
Awesome tool, get it into PyPi so we can pip install it 

### ISSUE THREAD

**Issue by geekpete** [eschwim/s3wipe#2]
Would be great if it was in PyPi so it can be installed with:

```
pip install s3wipe
```

If you need a hand with that, let me know.

**Comment by geekpete** [comment]
Also wondering, what was the use case that led you to write this tool? What type of data/files were you dealing with?

**Comment by eschwim** [comment]
Should be uploaded to PyPI now :grin:  

As for our use case, we (the Ops team at Redfin) have an S3 bucket that contains all of our website images.  We had accidentally created it in the us-east-1 AWS region, and only after the files were completely uploaded did we realize that we _really_ wanted it in us-west-2.  

Since there is no graceful way to move files between S3 regions, our only alternative was to delete the original bucket and all of its files (approximately 400 million images, spread across a directory hierarchy containing hundreds of thousands of sub directories), and then re-upload them to the correct region.  

"Oops!" :scream:
